#
# ~/.zshenv
#
# setting up environment
#

# use path_helper and /etc/paths.d on MacOS X
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

# gather info about the system
export OS_FAMILY=$(uname -s)
export OS_FLAVOR=$OS_FAMILY
export OS_RELEASE=$(uname -r)

if [ -f /etc/arch-release ]; then
    OS_FLAVOR='Arch'
elif [ -f /etc/debian_version ] || [ -f /etc/lsb-release ]; then
    OS_FLAVOR='Debian'
fi

export TERM=xterm-256color

export CLICOLOR=1
export LSCOLORS=exfxcxdxbxexexabagacad

export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'

# setup editor and pager
export EDITOR="subl -w -n"
export VISUAL=$EDITOR
export PAGER="less"
export LESS="--ignore-case --raw-control-chars"

export LC_COLLATE=C


# setup rbenv, if present
if which rbenv &> /dev/null; then
    export PATH="$HOME/.rbenv/bin:$PATH"çƒ
    eval "$(rbenv init -)"
fi

# setup pip
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE="$HOME/.pip/cache"

# setup golang
export GOPATH="$HOME/Projects/go"

# docker
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/andreas/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1


