#
# ~/.zshenv
#
# setting up environment
#

PROFILE_STARTUP=false
if [[ "$PROFILE_STARTUP" == true ]]; then
  zmodload zsh/zprof
  PS4=$'%D{%M%S%.} %N:%i> '
  exec 3>&2 2>"${XDG_CACHE_HOME:-$HOME/tmp}/zsh_startup.$$"
  setopt xtrace prompt_subst
fi

# use path_helper and /etc/paths.d on MacOS X
if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

export PATH="$HOME/.bin:/usr/local/sbin:$PATH"

# gather info about the system
export OS_FAMILY=$(uname -s)
export OS_FLAVOR=$OS_FAMILY
export OS_RELEASE=$(uname -r)

if [ -f /etc/arch-release ]; then
    OS_FLAVOR='Arch'
elif [ -f /etc/debian_version ] || [ -f /etc/lsb-release ]; then
    OS_FLAVOR='Debian'
fi

export TERM=xterm-256color

export CLICOLOR=1
export LSCOLORS=exfxcxdxbxexexabagacad

export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'

# setup editor and pager
export EDITOR="vim"
export VISUAL=$EDITOR
export PAGER="less"
export LESS="--ignore-case --raw-control-chars"

export LC_COLLATE=C

# homebrew
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

# setup rbenv, if present
if which rbenv &> /dev/null; then
    export PATH="$HOME/.rbenv/bin:$PATH"çƒ
    eval "$(rbenv init -)"
fi

#if which brew &> /dev/null && brew --prefix nvm &> /dev/null ; then
#    export NVM_DIR=~/.nvm
#    source $(brew --prefix nvm)/nvm.sh --no-use
#fi

# setup pip
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DOWNLOAD_CACHE="$HOME/.pip/cache"


###
# decide which one...

# setup autoenv
#source $(brew --prefix autoenv)/activate.sh

# setup direnv
if which direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi

#
###

if which gpgconf &> /dev/null; then
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
fi

# load local environment
if [ -f "$HOME/.zshenv-private" ]; then
  source "$HOME/.zshenv-private" ]
fi

if [[ "$PROFILE_STARTUP" == true ]]; then
  zprof
  unsetopt xtrace
  exec 2>&3 3>&-
fi

export GOPATH="$HOME/.go"
export GO111MODULE=on
export PATH="$PATH:$GOPATH/bin"


