export ZSH_HOME=~/.zsh
fpath=($ZSH_HOME/lib $fpath)
fpath+=("$ZSH_HOME/pure")

autoload -U promptinit; promptinit
prompt pure
source $ZSH_HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# do not beep
setopt no_beep

setopt autocd
setopt extendedglob

export CLICOLOR=1

# load config files
for f in $ZSH_HOME/lib/*.zsh; do
    source $f
done



[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
