
#zmodload zsh/zprof
autoload -U colors && colors

export ZSH_HOME=~/.zsh
fpath+=("$ZSH_HOME/lib")

source $ZSH_HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

setopt auto_cd
setopt auto_pushd

setopt extended_glob

# do not beep
setopt no_beep


export CLICOLOR=1


# this is needed to get git & ssh to work with the GPG key
if which gpg-connect-agent &> /dev/null; then
  export GPG_TTY=$(tty)
  gpg-connect-agent updatestartuptty /bye >/dev/null
fi

# load fzf when present
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# load config files
for f in $ZSH_HOME/lib/*.zsh; do
    source $f
done


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"


# load local environment
if [ -f "$HOME/.zshrc-private" ]; then
  source "$HOME/.zshrc-private" ]
fi


#zprof

