#!/usr/bin/env bash

if ! [ $(which brew) ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

brew install \
    autoenv \
    cmake \
    dnsmasq \
    flow \
    gnupg2 \
    hostmux \
    keybase \
    maven \
    mplayer \
    nvm \
    sox \
    ssh-copy-id \
    tmux
    zsh-completions


brew cask install google-chrome \
    coconutbattery \
    macvim \
    robomongo \
    sequel-pro \
    spectacle \
    the-unarchiver
#brew cask install sublime-text3
#brew cask install carbon-copy-cloner
#brew cask install instacast
#brew cask install moneymoney
#brew cask install the-unarchiver
#brew cask install virtualbox
#brew cask install vagrant


