#!/usr/bin/env bash

if ! [ "$(command -v brew)" ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew update

brew install \
    cmake \
    direnv \
    dnsmasq \
    gnupg2 \
    hukl/tap/hostmux \
    maven \
    n \
    ssh-copy-id \
    tmux \
    zsh-completions


brew cask install google-chrome
brew cask install coconutbattery
brew cask install keybase
brew cask install macvim --no-binaries
brew cask install rectangle
brew cask install the-unarchiver

#brew cask install sublime-text3
#brew cask install carbon-copy-cloner
#brew cask install instacast
#brew cask install moneymoney
#brew cask install the-unarchiver
#brew cask install virtualbox
#brew cask install vagrant

