#!/usr/bin/env bash

if [ $(which brew 1> /dev/null) ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

brew install clib gnupg2 gpg-agent keybase lua luarocks node zsh-completions
brew install --cocoa -srgb emacs

brew install caskroom/cask/brew-cask
brew cask tap caskroom/versions

brew cask install google-chrome
brew cask install coconutbattery
brew cask install sublime-text3
brew cask install carbon-copy-cloner
brew cask install instacast
brew cask install moneymoney
brew cask install the-unarchiver
brew cask install virtualbox
brew cask install vagrant


